-- Schema + demo RLS policies for the Supabase + Spring + Metro DI sample.
-- Run in the Supabase SQL editor (or `supabase db push`).
--
-- The backend talks to PostgREST with the ANON key, so each table needs a policy
-- that lets the anon role read/write it. These policies are intentionally
-- permissive for a demo; a real app would scope rows to auth.uid().

-- Users -----------------------------------------------------------------------
create table if not exists public.users (
    id           uuid        primary key default gen_random_uuid(),
    email        text        not null unique,
    display_name text        not null,
    created_at   timestamptz not null default now()
);

alter table public.users enable row level security;

drop policy if exists "anon full access (demo)" on public.users;
create policy "anon full access (demo)"
    on public.users for all to anon using (true) with check (true);

-- Products --------------------------------------------------------------------
create table if not exists public.products (
    id          bigint generated by default as identity primary key,
    name        text        not null,
    description text,
    price       numeric     not null default 0,
    created_at  timestamptz not null default now()
);

alter table public.products enable row level security;

drop policy if exists "anon full access (demo)" on public.products;
create policy "anon full access (demo)"
    on public.products for all to anon using (true) with check (true);
